# Layer on top of docker-compose.yml which uses volumes
# to share application data between nginx, the app, and
# the workers.
#
# You will still need one more layer on top, defining the
# various usernames and passwords, and which ports should
# be opened.

# Need v2 so we can set resource limits without Swarm
version: '2.4'

services:
  nginx:
    volumes:
      - app_public_data:/app/public/storage:ro

  app:
    volumes:
      - app_data:/app/storage
      - app_public_data:/app/storage/public

  java-worker:
    volumes:
      - app_data:/app/storage
      - app_public_data:/app/storage/public:ro
      - m2_data:/home/www-data/.m2

  default-worker:
    volumes:
      - app_data:/app/storage
      - app_public_data:/app/storage/public

volumes:
  app_data:
    driver: local
  app_public_data:
    driver: local
